#pragma once

#define NOT_ENOUGH_ARGUMENTS -1
#define INVALID_OPERATION_ARGUMENT -2
#define INVALID_ORIGIN_FILE_ARGUMENT -3
#define INVALID_DESTINATION_FILE_ARGUMENT -4
#define INVALID_COPY_OPERATION -5
#define INVALID_CUT_OPERATION -6